parameters:
#    power_grid.example.class: PowerGrid\PowerGridBundle\Example

services:
#    power_grid.example:
#        class: %power_grid.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
